feat: user 서비스 구현
gum-la-yu-dong/backend pull request #7
Opened 2021-06-27 14:37 UTC by YounghoonKwon

2021-06-27 15:38 UTC, Livenow14 requested changes

2021-06-27 15:38 UTC, Livenow14 commented on gumrya-core/src/main/java/gumrya/user/domain/repository/UserRepository.java
> +    boolean existsByEmail(String email);
Long deleteByEmail(String email);
에서 Long을 반환하는 이유가 있을까요??

추가적으로 작성한 쿼리에 대해 테스트 코드도 작성 부탁드려요.

2021-06-27 15:38 UTC, Livenow14 commented on gumrya-web/src/main/java/gumrya/service/UserService.java
> +        return new UserResponse(saveUser);
```suggestion
        User user = new User(userRequest.getEmail(), userRequest.getPassword(), userRequest.getNickname(),
                userRequest.getIntroduction(), userRequest.getProfileUrl(), userRequest.getGithubUrl());
                
        User saveUser = userRepository.save(user);
        return new UserResponse(saveUser);
```
흐름이 변경되는곳에 줄을 띄워줘도 괜찮을거같아요

2021-06-27 15:38 UTC, Livenow14 commented on gumrya-web/src/test/java/gumrya/service/UserServiceTest.java
> +                        ".com/younghoonkwon");
```suggestion
                "github" +
                        ".com/younghoonkwon");
```
라이언만의 이유가 있는 줄바꿈일까요??!

2021-06-27 15:38 UTC, Livenow14 commented on gumrya-web/src/test/java/gumrya/service/UserServiceTest.java
> +        assertThatThrownBy(() -> userService.save(userRequest)).isInstanceOf(DuplicateException.class);
```suggestion
        assertThatThrownBy(() -> userService.save(userRequest))
        .isInstanceOf(DuplicateException.class);
```
줄바꿈을 하는 것을 컨벤션으로 잡아도 괜찮을거같아요(검증 대상이 많아질 경우 줄바꿈이 필요하기 때문)

2021-06-27 15:38 UTC, Livenow14 commented on gumrya-web/src/test/java/gumrya/service/UserServiceTest.java
> +        assertThat(findEmail).isEqualTo(userResponse);
UserResponse가 검증에 한번 쓰이는데. 이를 인스턴스화를 하는것은 테스트 목적에 떨어진다 생각해요.

조회시에는 인스턴스 필드로 선언되어있는 userRequest의 email 필드를  userService.findByEmail의 인자로 넘겨주고,
검증시에는 response와 request의 값을 비교해도 좋을 듯 해요. 
이는 이후 테스트에도 동일 적용할 수 있을 거 같아요.

2021-06-27 15:51 UTC, YounghoonKwon commented on gumrya-web/src/test/java/gumrya/service/UserServiceTest.java
> +        assertThat(findEmail).isEqualTo(userResponse);
의도한게 맞는지는 모르겠지만 수정 했습니다

2021-06-28 01:39 UTC, Livenow14 commented
## 수정사항
1. willthrow -> Optional.empty() 변경 
2. DisplayName -> 실패 한다음 이유 
3. response 네이밍 명시

2021-06-28 02:25 UTC, Livenow14 approved these changes
lgtm

2021-06-28 02:25 UTC, merged